yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      eslint: "^7.29.0"
      "@babel/core": "^7.16.0"
  "@fifty-short/api@*":
    peerDependenciesMeta:
      knex:
        optional: true
  "@nuxt/babel-preset-app@*":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "^7.16.0"
  "@nuxtjs/stylelint-module@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "@vue/test-utils@*":
    peerDependenciesMeta:
      vue:
        optional: true
      vue-template-compiler:
        optional: true
  "eslint-plugin-vue@*":
    peerDependenciesMeta:
      eslint:
        optional: true
  "eslint-webpack-plugin@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "nuxt@*":
    dependencies:
      consola: "^2.15.3"
  "sass-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "vue-eslint-parser@*":
    peerDependenciesMeta:
      eslint:
        optional: true
    dependencies:
      "@babel/eslint-parser": "^7.14.7"
  "vue-jest@*":
    peerDependenciesMeta:
      vue:
        optional: true
      vue-template-compiler:
        optional: true
  "vue-loader@*":
    peerDependenciesMeta:
      "@vue/compiler-sfc":
        optional: true
  "vuetify@*":
    peerDependenciesMeta:
      vue:
        optional: true
  "vuetify-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
      vue-template-compiler:
        optional: true
